- hosts: docker
  become: yes
  tasks:
    - name: Deploy Apps
      docker_container:
        name: share-admin
        image: 20.100.1.191:5000/smf/smartincome-test:<tag_placeholder>
        state: started
        recreate: yes
        ports:
          - "8300:8300"